png(filename="~/Desktop/figura1.png", height=480, width=640, bg="white");
plot(data$zChaff, type="o", col=plot_colors[1], ylim=c(0,max_y), axes=FALSE, ann=FALSE);
axis(1, at=1:60, lab=1:60);
axis(2, las=1, at=3*0:max_y);
lines(data$KECOSATS, type="o", pch=22, lty=2, col=plot_colors[2]);
lines(data$KECOSATS_con_learning, pch=23, lty=3, col=plot_colors[3]);
title(main="Comparativa KECOSATS vs zChaff", col.main="red", font.main=4);
title(xlab="Caso de prueba", col.lab=rgb(0,0.5,0));
title(ylab= "Tiempo(s)", col.lab=rgb(0,0.5,0));
legend(1, max_y, names(data), cex=0.8, col=plot_colors, pch=21:23, lty=1:3);
dev.off();
