png(filename="~/Desktop/figura2.png", height=480, width=640, bg="white");
plot(data$SinAprendizaje, type="o", col=plot_colors[1], ylim=c(0,max_y), axes=FALSE, ann=FALSE);
axis(1, at=1:4, lab=14:17);
axis(2, las=1, at=500*0:max_y);
lines(data$ConAprendizaje, type="o", pch=22, lty=2, col=plot_colors[2]);
title(main="Num. nodos expandidos N-reinas. Comparacion con y sin aprendizaje KECOSATS", col.main="red", font.main=4);
title(xlab="Problema n-reinas (n)", col.lab=rgb(0,0.5,0));
title(ylab= "Numero de nodos expandidos", col.lab=rgb(0,0.5,0));
legend(1, max_y, names(data), cex=0.8, col=plot_colors, pch=21:23, lty=1:3);
dev.off();
